[build]
pre-build = [
    "apt-get install -y unzip",
    "curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v28.3/protoc-28.3-linux-x86_64.zip",
    "unzip protoc-28.3-linux-x86_64.zip -d protoc3",
    "mv protoc3/bin/* /usr/local/bin/",
    "mv protoc3/include/* /usr/local/include/",
    "chmod +x /usr/local/bin/protoc"
]