FROM python:3.9-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY mypeer/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY mypeer/ /app/
ENTRYPOINT ["python3", "main.py"]
