# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zab_client.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'zab_client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10zab_client.proto\x12\nzab_client\x1a\x0btypes.proto\x1a\x1bgoogle/protobuf/empty.proto\"D\n\x17WriteTransactionRequest\x12)\n\x0btransaction\x18\x01 \x01(\x0b\x32\x14.zab.BankTransaction\"(\n\x12ReadAccountRequest\x12\x12\n\naccount_id\x18\x01 \x01(\r\"&\n\x13ReadAccountResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x05\"O\n\'DebugHasOutstandingTransactionsResponse\x12$\n\x1chas_outstanding_transactions\x18\x01 \x01(\x08\x32\x80\x03\n\x10ZabClientService\x12Q\n\x10WriteTransaction\x12#.zab_client.WriteTransactionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12P\n\x0bReadAccount\x12\x1e.zab_client.ReadAccountRequest\x1a\x1f.zab_client.ReadAccountResponse\"\x00\x12U\n\x10\x44\x65\x62ugReadAccount\x12\x1e.zab_client.ReadAccountRequest\x1a\x1f.zab_client.ReadAccountResponse\"\x00\x12p\n\x1f\x44\x65\x62ugHasOutstandingTransactions\x12\x16.google.protobuf.Empty\x1a\x33.zab_client.DebugHasOutstandingTransactionsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zab_client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITETRANSACTIONREQUEST']._serialized_start=74
  _globals['_WRITETRANSACTIONREQUEST']._serialized_end=142
  _globals['_READACCOUNTREQUEST']._serialized_start=144
  _globals['_READACCOUNTREQUEST']._serialized_end=184
  _globals['_READACCOUNTRESPONSE']._serialized_start=186
  _globals['_READACCOUNTRESPONSE']._serialized_end=224
  _globals['_DEBUGHASOUTSTANDINGTRANSACTIONSRESPONSE']._serialized_start=226
  _globals['_DEBUGHASOUTSTANDINGTRANSACTIONSRESPONSE']._serialized_end=305
  _globals['_ZABCLIENTSERVICE']._serialized_start=308
  _globals['_ZABCLIENTSERVICE']._serialized_end=692
# @@protoc_insertion_point(module_scope)
