# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: types.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btypes.proto\x12\x03zab\"&\n\x04ZxId\x12\r\n\x05\x65poch\x18\x01 \x01(\r\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\r\"1\n\x04Vote\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1d\n\nlast_zx_id\x18\x02 \x01(\x0b\x32\t.zab.ZxId\"5\n\x0f\x42\x61nkTransaction\x12\x12\n\naccount_id\x18\x01 \x01(\r\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"V\n\x17\x42\x61nkTransactionMapEntry\x12\x16\n\x03key\x18\x01 \x01(\x0b\x32\t.zab.ZxId\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.zab.BankTransaction\"C\n\x12\x42\x61nkTransactionMap\x12-\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1c.zab.BankTransactionMapEntry\"\xaa\x01\n\x07History\x12&\n\x13last_commited_zx_id\x18\x01 \x01(\x0b\x32\t.zab.ZxId\x12 \n\rold_threshold\x18\x02 \x01(\x0b\x32\t.zab.ZxId\x12)\n\x08proposed\x18\x03 \x01(\x0b\x32\x17.zab.BankTransactionMap\x12*\n\tcommitted\x18\x04 \x01(\x0b\x32\x17.zab.BankTransactionMap\"o\n\x04Snap\x12\x1d\n\x02\x64\x62\x18\x01 \x03(\x0b\x32\x11.zab.Snap.DbEntry\x12\x1d\n\x07history\x18\x02 \x01(\x0b\x32\x0c.zab.History\x1a)\n\x07\x44\x62\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"5\n\x04\x44iff\x12-\n\x0ctransactions\x18\x01 \x01(\x0b\x32\x17.zab.BankTransactionMap\"/\n\x05Trunc\x12&\n\x13last_commited_zx_id\x18\x01 \x01(\x0b\x32\t.zab.ZxId*1\n\x05State\x12\x0c\n\x08\x45lection\x10\x00\x12\r\n\tFollowing\x10\x01\x12\x0b\n\x07Leading\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SNAP_DBENTRY']._loaded_options = None
  _globals['_SNAP_DBENTRY']._serialized_options = b'8\001'
  _globals['_STATE']._serialized_start=713
  _globals['_STATE']._serialized_end=762
  _globals['_ZXID']._serialized_start=20
  _globals['_ZXID']._serialized_end=58
  _globals['_VOTE']._serialized_start=60
  _globals['_VOTE']._serialized_end=109
  _globals['_BANKTRANSACTION']._serialized_start=111
  _globals['_BANKTRANSACTION']._serialized_end=164
  _globals['_BANKTRANSACTIONMAPENTRY']._serialized_start=166
  _globals['_BANKTRANSACTIONMAPENTRY']._serialized_end=252
  _globals['_BANKTRANSACTIONMAP']._serialized_start=254
  _globals['_BANKTRANSACTIONMAP']._serialized_end=321
  _globals['_HISTORY']._serialized_start=324
  _globals['_HISTORY']._serialized_end=494
  _globals['_SNAP']._serialized_start=496
  _globals['_SNAP']._serialized_end=607
  _globals['_SNAP_DBENTRY']._serialized_start=566
  _globals['_SNAP_DBENTRY']._serialized_end=607
  _globals['_DIFF']._serialized_start=609
  _globals['_DIFF']._serialized_end=662
  _globals['_TRUNC']._serialized_start=664
  _globals['_TRUNC']._serialized_end=711
# @@protoc_insertion_point(module_scope)
